import '../styles/globals.css';
import { NextUIProvider } from '@nextui-org/react';
import Head from 'next/head'
import Header from './../components/Header';

function MyApp({ Component, pageProps }) {
  return <NextUIProvider>
  <Head>
    <title>Interview IT</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/Quizlet.jpg" />
  </Head>
    <Header />
    <Component {...pageProps} />
  </NextUIProvider>
}

export default MyApp
